name: Validate JIRA TItle

on:
    pull_request:
        types: [opened, reopened, synchronize]

jobs:
    validate-jira-title:
        name: Validate JIRA Title
        runs-on: ubuntu-latest

        steps:

            - name: Validate JIRA Title
              uses: actions/github-script@v7.0.1
              env:
                TITLE: ${{ github.event.pull_request.title }}
              with:
                result-encoding: string
                github-token: ${{ secrets.GITHUB_TOKEN }}
                script: |
                    const jiraRegex = /^(Revert ")?\[(XBMAPI|XBMPUR|XBMSAL|XAAC|XBMSTA|SALXAA|XBR|XIT|MOBPLAT)-\d{1,4}\]/;
                    const titleStartsWithAJira = jiraRegex.test(process.env.TITLE);

                    if (!titleStartsWithAJira){
                        const title = "Missing JIRA in the title";
                        const body = 'The title of this PR needs to start with a JIRA e.g. [PROJECT-1234] My PR';
                            console.error(` ${title} - ${body} `);
                            process.exit(1);
                    }

                    


