name: Validate JIRA TItle

on:
    pull_request:
        types: [opened, reopened, synchronize]

jobs:
    validate-jira-title:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Validate JIRA Title
              uses: actions/github-script@v7.0.1
              with:
                github-token: ${{ secrets.GITHUB_TOKEN }}
                script: |
                    const payload = context.payload
                    const prTitle = payload.pull_request.title;
                    const jiraRegex = /^(Revert ")?\[(XBMAPI|XBMPUR|XBMSAL|XAAC|XBMSTA|SALXAA|XBR|XIT|MOBPLAT)-\d{1,4}\]/;
                
                    if (!jiraRegex.test(prTitle)){
                        const title = "Missing JIRA in the title";
                        if (github.context.payload.pull_request.labels.find(label => label.name === 'documentation')){
                            const body = 'There was no JIRA found in the title. However, as these are documentation only changes it is not required.';
                            console.warn(` ${title} - ${body}`);
                        }else{
                            const body = 'The title of this PR needs to start with a JIRA e.g. [PROJECT-1234] My PR';
                            console.error(` ${title} - ${body} `);
                            process.exit(1);
                        }
                    }

                    


